asset_path: /legged_lab/assets/ths_23dof/urdf/ths_23dof.urdf             # URDF 模型文件的绝对路径
usd_dir: /legged_lab/assets/ths_23dof/usd                                # 生成的 USD 文件存放目录
usd_file_name: ths_23dof.usd                                             # 生成的 USD 文件名
force_usd_conversion: true                                               # 强制进行 URDF 到 USD 的转换（即使已有 USD 文件）
make_instanceable: true                                                  # 在 USD 中将模型设为可实例化，提升场景复用性能
fix_base: false                                                          # 不固定机器人基座（允许基座自由运动）
root_link_name: null                                                     # 根链接名称为空（使用 URDF 中的原始根链接）
link_density: 0.0                                                        # 连杆密度为 0（可能表示不计算质量或使用默认质量）
merge_fixed_joints: true                                                 # 合并固定关节以减少不必要的层级结构
convert_mimic_joints_to_normal_joints: false                             # 不将模仿关节（mimic joints）转换为普通关节

joint_drive:                                                   # 关节驱动参数配置
  drive_type: force                                            # 驱动类型为力（force）控制
  target_type: none #position                                  # 无特定目标类型（如位置、速度目标）
  gains:                                                       # 驱动增益参数
    stiffness: 0.0 #100.0                                      # 刚度为 0（无弹性反馈）
    damping: 0.0 #1.0                                          # 阻尼为 0（无速度反馈）
collider_type: convex_hull                                     # 碰撞体类型使用凸包近似
self_collision: false                                          # 禁用自碰撞检测
replace_cylinders_with_capsules: false                         # 不将圆柱体替换为胶囊体
collision_from_visuals: false                                  # 不从视觉网格生成碰撞体
##
# Generated by UrdfConverter on 2026-01-06 at 18:33:34.
##



